### ISSUE TITLE
Update nuget with the latest version

### ISSUE THREAD

**Issue by alexmaris** [mikeobrien/Conejo#1]
Hi Mike - I'm not sure if it's something on my end, but is v1.0.11 that's up on Nuget different than what's currently on the master branch? It seems that the RabbitMQ.Client lib had a breaking change in version 3.5.5+ (possibly as early as 3.4) that's causing a breaking change to Conejo v1.0.11. Are you seeing the same on your end?

**Comment by mikeobrien** [comment]
I haven't used it in a long time but I bumped the dependencies to the latest. Pushed the nuget so it should be available (v1.0.12).

**Comment by alexmaris** [comment]
Very cool, can confirm that it's working nicely with RabbitMQ.Client 3.5.6.

Thank you!

**Comment by mikeobrien** [comment]
Awesome, glad it worked!
